/** English copy for /admin and superadmin shell only; rest of app stays on main locale (German). */
export const adminEn = {
  title: 'Administration',
  /** Top bar when superadmin is restricted to admin routes only */
  logOut: 'Log out',
  forbidden: 'Access denied. Only super administrators can use this page.',
  companies: 'Companies',
  users: 'Users',
  companyName: 'Name',
  createdAt: 'Created',
  userEmail: 'Email',
  userCompany: 'Company',
  userRole: 'Role',
  newCompany: 'New company',
  createCompany: 'Create company',
  newUser: 'Create user',
  assignUser: 'Assign user',
  assignCompany: 'Company',
  assignSubmit: 'Save assignment',
  selectCompany: 'Please select a company.',
  assignMissing: 'Please select both a user and a company.',
  passwordHint: 'At least 6 characters.',
  userPlaceholder: 'Select user',
  companyPlaceholder: 'Select company',
  roleUser: 'User',
  roleAdmin: 'Admin',
  roleSuperadmin: 'Superadmin',
  loading: 'Loading…',
  email: 'Email address',
  password: 'Password',
} as const;
